### ISSUE TITLE
Pilot, Xi-CAM and timing of intake-bluesky

### ISSUE THREAD

**Issue by dylanmcreynolds** [lightsources/project-management#2]
For integrating Xi-CAM to Bluesky, a question comes up about whether to integrate directly to Databroker or to intake-bluesky (or both?) for getting data back from Bluesky. Is there a known timing for the intake-bluesky project to be usable for the pilot?

**Comment by ronpandolfi** [comment]
@dylanmcreynolds I think the question as posed in earlier discussion is if (when?) intake-bluesky allows accessing data from databroker instances already deployed at NSLS-II (from old-style DB).

After thinking about this a bit more, I suspect the answer is yes. Since both utilize `event-model` for structuring their event-model data, and the 'serialization' of that to mongo is simple, I expect that intake-bluesky would already function with the previously deployed DB instances.

So, the precise question should be _when will the intake-bluesky api will be ready to develop against_?

**Comment by danielballan** [comment]
Yes, that is the right question. I would add that if we focus on _interfaces that consume a stream of documents_, those will generalize to what `databroker` is today, the soon-to-land databroker-on-intake rewrite of `databroker`, and documents coming from the live data acquisition, and ingested files. The part of the code that has to deal with specific details of each of these access modes should be thin---at least that's how it has worked out in `bluesky-browser` so far.

My goal is to land databroker 1.0 by the end of this month. That work is happening in https://github.com/bluesky/databroker/pull/392. Effort has recently been diverted to [improving intake itself](https://github.com/intake/intake/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3Adanielballan), but now the decks are cleared for @gwbischof and I to get it across the finish line. The databroker 1.0 release will include:

1. Some intake "drivers" (plugins for reading certain serializations) and the intake API. That is, `from databroker import Catalog` will give you same thing as `from intake import Catalog`.
2. A wrapper around `intake.Catalog` that provides an interface compatible with the old `Broker` API. This will enable old user code to opt in to the intake-backed system with only a one-line change.
3. The existing (pre-intake) databroker codebase, as a fallback for if/when we encounter problems with (2) in production. That is, `from databroker import Broker; Broker.named('...')` will give you exactly what is gives you now, relying on all the old, production-tested codepaths.

At some point in the future, (3) will be removed and we'll rely solely on (2) for backward-compatibility.

All three modes will be able to work with existing databases. Modes (1) and (2) will be able to work with new kinds of storage as well, such as msgpack and JSONL.

**Comment by danielballan** [comment]
Revisiting the original post:

> For integrating Xi-CAM to Bluesky, a question comes up about whether to integrate directly to Databroker or to intake-bluesky (or both?)

Integrate directly with databroker 1.0.0, using the `databroker.v2` interface. If we run into things that v2 cannot do that were possible with the v0/v1 interface, we can access those from the same library. Now that 1.0.0a1 has been released, I think we can close this issue and begin work on #4. Agree?

**Comment by dylanmcreynolds** [comment]
Agreed. This can be closed. For my part, I will continue to work on https://github.com/lightsources/project-management/issues/14 and switch over to using the Databroker repo rather than the intake-bluesky repo.
