### ISSUE TITLE
Add pip install support to pydm/typhon

### ISSUE THREAD

**Issue by ronpandolfi** [lightsources/project-management#34]

**Comment by teddyrendahl** [comment]
`PyDM` is on PyPI.

Typhon is pip installable, we now test installing it this way on our CI
https://github.com/pcdshub/typhon/blob/e595fb2dc015f396523b1357c8d5ab84e0b53bb7/.travis.yml#L66

Unfortunately, there is already a project called `typhon` on PyPI. It appears to be pretty actively developed so I doubt they are willing to give it up.

**Comment by mrakitin** [comment]
I have a few suggestions for the PyPI name:
- `t4n` (`k8s` style)
- `ty4n`
- `'typhon'[::-1]` (should be interpreted)

**Comment by klauer** [comment]
typhos is installable through PyPI now: `pip install typhos pyqt5 && typhos --fake-device ophyd.EpicsMotor[]` worked for me. I think we can close this.

**Comment by ronpandolfi** [comment]
Agreed, thank you all! 👍
