### ISSUE TITLE
scikit-beam and pypi

### ISSUE THREAD

**Issue by dylanmcreynolds** [lightsources/project-management#52]
There is some work to do to get scikit-beam to install on pypi.

**Comment by mrakitin** [comment]
The package is tagged on GitHub, but I don't seem to have rights to push to PyPI. Asked @danielballan to add me to the list of maintainers, so I can push the latest (and missing) versions. 

Please note, it's a source distribution (`sdist`) only for now, meaning the compilation will be needed during the installation step. We can enable the integration with Azure Pipelines/TravisCI later to produce the wheels for all platforms. Conda already has the packages for all platforms in our new `nsls2forge` channel:
- https://anaconda.org/nsls2forge/scikit-beam/files (conda packages)
- https://github.com/nsls-ii-forge/scikit-beam-feedstock (the feedstock repo with the recipe)

**Comment by danielballan** [comment]
@mrakitin has been granted access on PyPI and has updated the published releases there. I think this addresses the immediate need. I propose that we close this an open a separate issue on the scikit-beam repo to track adding wheels on all platforms.

**Comment by mrakitin** [comment]
That sounds reasonable to me.

**Comment by mrakitin** [comment]
Tracked now via https://github.com/scikit-beam/scikit-beam/issues/555.
