### ISSUE TITLE
Merge XPCS and SAXS Xi-CAM plugins into single Scattering plugin

### ISSUE THREAD

**Issue by dylanmcreynolds** [lightsources/project-management#53]
Naming of new plugin TBD.

**Comment by ambarb** [comment]
What happens to XPCS data for WAXS or have to do SAXS in a non-traditional way (i.e., the CCD field of view is smaller than a full SAXS pattern)?

**Comment by dylanmcreynolds** [comment]
Adding @ronpandolfi  and @ihumphrey to this conversation.

**Comment by dylanmcreynolds** [comment]
@ihumphrey  Is this done or in a PR?

**Comment by dylanmcreynolds** [comment]
Work is being done here: https://github.com/synchrotrons/Xi-cam.SAXS/tree/merge-xpcs-new

**Comment by dylanmcreynolds** [comment]
Completed with https://github.com/synchrotrons/Xi-cam.SAXS/pull/7
