### ISSUE TITLE
Conda Packages for Xi-cam

### ISSUE THREAD

**Issue by dylanmcreynolds** [lightsources/project-management#66]

**Comment by dylanmcreynolds** [comment]
NSLS-II prefers to use conda streams to distribute software on beamline computer. So xi-cam packages will be created.

xicam base stream
- xicam
- xicam.core
- xicam.gui
- xicam.plugin

plugin stream
- xicam.saxs/xpcs (name?)

**Comment by mrakitin** [comment]
It is indeed a high priority for us to distribute the software seamlessly using conda to the beamlines which want to use it.

**Comment by tacaswell** [comment]
@jklynch has started to look at this.

**Comment by dylanmcreynolds** [comment]
I sent an invite to @jklynch to join this org.

**Comment by dylanmcreynolds** [comment]
I invited @jklynch to join this org, but he's not there yet. Assigned to @mrakitin .

**Comment by stuartcampbell** [comment]
Hi @jklynch, Any updates or progress?

**Comment by dylanmcreynolds** [comment]
I think this is done, yes @jklynch @mrakitin ? There might be ongoing bits and pieces? If so, can you close it?

**Comment by mrakitin** [comment]
Yes, the packages' feedstocks are available in https://github.com/nsls-ii-forge (search for `xicam`), and the core packages have been built and available in the (`nsls2forge`)[https://anaconda.org/nsls2forge/repo] conda channel. The maintenance burden can be shared between the teams (@ihumphrey submitted a few PRs to the feedstock repos already when the new versions had been released).
