### ISSUE TITLE
Dark images as part of run scan

### ISSUE THREAD

**Issue by dylanmcreynolds** [lightsources/project-management#71]
At CSX currently, getting dark frame involves looking for previous runs where the dark was collected. Dan mentioned that at CSX, there has been talk about updating their streams so that a dark frame comes with every run. This would be very helpful for the Phase1 demo.

**Comment by danielballan** [comment]
@mrakitin, @jklynch, and I had meeting where we went over the bluesky-darkframes documentation and formed theory about how to apply bluesky-darkframes at CSX.

There is a detail at CSX that we haven't yet encountered at the beamlines where bluesky-darkframes has been applied to so far: they take dark frames over a range of gain settings. There are couple ways we could bundle together these frames with different gain settings:

1. As different runs (which is what CSX does now)
2. As different fields in one event using `ophyd.area_detector.trigger_mixins.MultiTrigger` 
2. As different Events in one stream
4. As different Events in separate streams

Our discussion led to the conclusion that (4) has clear advantages. It could be implemented by instantiating multiple `DarkFramePreprocessors`, one per gain setting. Untested sketch:

```py
import functools
from bluesky_darkframes import DarkFramePreprocessor

def dark_plan(gain_level):                                                                                      
    ...        
                                                                                                 
GAIN_SETTINGS = [4, 8, 16]
for gain in GAIN_SETTINGS:                                                         
    dark_frame_preprocessor = DarkFramePreprocessor(dark_plan=functools.partial(dark_plan,                      
    gain_level=gain, stream_name=f'dark_gain_{gain}'))                                                          
    RE.preprocessors.append(dark_frame_preprocessor) 
```

**Comment by danielballan** [comment]
Oh, and to keep everyone in the loop on where this work stands, @ambarb is currently coordinating with other staff about when would be a good time to configure and test this.

**Comment by dylanmcreynolds** [comment]
Is there update on this? If there is something we need to do in xi-cam to use this, we're running short on time.

**Comment by dylanmcreynolds** [comment]
We talked about getting a run with this new configuration to @ihumphrey  so that we can make changes in xi-cam to use them. Adding Ian as an assignee for that hand-off.

**Comment by dylanmcreynolds** [comment]
If we could get that sample run early this week, we could have time to code its use into into xi-cam. Is getting this to us possible, @danielballan ?

**Comment by dylanmcreynolds** [comment]
Work was complete and used for the demo successfully.
