### ISSUE TITLE
Test integration of codes from CSX meeting with Xi-Cam

### ISSUE THREAD

**Issue by dylanmcreynolds** [lightsources/project-management#76]
Much coding was done and many branches were updated at NSLS-II this week. We'd like to perform a test to make sure that X-Cam is still running well with the code.

**Comment by danielballan** [comment]
Can we declare victory on this one?

**Comment by dylanmcreynolds** [comment]
Yes. Yes we can. We still have to work through the issue of exactly where and how the csx-specific code is run, but the overall integration for the demo was a success.
