### ISSUE TITLE
Resolve HDF5 access issues. 

### ISSUE THREAD

**Issue by danielballan** [lightsources/project-management#82]
While we do have a "fix" in https://github.com/bluesky/area-detector-handlers/pull/3 we have been unable to isolate the underlying problem that it is apparently fixing.

**Comment by dylanmcreynolds** [comment]
This has been fixed, no?

**Comment by dylanmcreynolds** [comment]
Is this still open?

**Comment by mrakitin** [comment]
I think so.

**Comment by danielballan** [comment]
Sorry I'm late to this party. Cross-posted from bluesky/area-detector-handlers#3, which I have just closed:

> The theory behind this fix turned out not to be correct. We have not observed the problem in several months now; it may have been due to known (and fixed) thrash-y resource management in databroker.

Without fully understanding the problem we can't say definitively that it has been resolved, but I think we should close this unless/until it is observed again.
