### ISSUE TITLE
Catalog load performance issue

### ISSUE THREAD

**Issue by dylanmcreynolds** [lightsources/project-management#87]
We have seen issues loading large numbers of catalogs into xi-cam through databroker. This has something to do with dask hashing the entire dictionary in the document stream (which involves lots of sorts in order to canoncialize the dict).

This is being worked on here. https://github.com/bluesky/databroker/pull/483

Dylan will test this PR.

**Comment by danielballan** [comment]
Recently databroker beta releases have pushed down the load times from ~250ms to ~15ms. This is satisfactory from a usability point of view: catalogs now load faster than you can skim them as you scroll.
